twitPuzzle-server/config/routes.rb
TwitPuzzle::Application.routes.draw do
  resources :rankings

  resources :users

  resources :users do
    resources :puzzles
  end
  resources :logins
  resources :friend do
    collection do
      get 'follow'
      get 'follower'
    end
  end

  resources :puzzles do
     member do
      get 'get_image'
     end
   end

resources :users do 
  resources :rankings
end

  resources :users do
    collection do
      get 'self_profile'
    end
  end

  TwitPuzzle::Application.routes.draw do
    get "rankings/eachRanking/:puzzle_id" => "rankings#eachRanking"
  end

  TwitPuzzle::Application.routes.draw do
    get "users/search/:name" => "users#searchID"
  end

  TwitPuzzle::Application.routes.draw do
    get "users/profile/self" => "users#self_profile"
  end

  TwitPuzzle::Application.routes.draw do
    get "puzzles/user/:user_id" => "puzzles#user_puzzle"
  end

  root to: 'logins#new'

end

twitPuzzle-server/app/models/user.rb
class User < ActiveRecord::Base
	has_many :puzzles 
	has_many :rankings
	validates_uniqueness_of(:name)
  validates_uniqueness_of(:email)
  validates_presence_of :name, :email, :password

	def registered?
		user_obj = User.where(email: self.email).first
		if user_obj && user_obj.password == self.password
			self.id = user_obj.id
			true
		else	
			false
		end
	end
end

twitPuzzle-server/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit

  end

  def self_profile
    @profile = User.find("#{session[:login]}")

    followNum = Friend.where("user_id='#{session[:login]}'")
    followerNum = Friend.where("friend_id='#{session[:login]}'")
    puts "created:at::::",@profile.created_at
    @profile_results = {:id=>@profile.id, :name=>@profile.name, :created_at=>@profile.created_at, :followNum=>followNum.size, :followerNum=>followerNum.size}


  end

  def searchID
    @users = User.where("name='#{params[:name]}'")

    @search_results = []
    for user in @users
      f = Friend.where("user_id='#{session[:login]}' and friend_id=#{user.id}")
      if f.size>0
        friendState = "アンフォロー"
      else
        friendState = "フォロー"
      end
      @search_results.push(:id=>user.id, :name=>user.name, :friendState=>friendState, :created_at=>user.created_at )
    end

  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        puts "True::"
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        puts "False::"
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password)
    end
end

twitPuzzle-server/app/helpers/users_helper.rb
module UsersHelper
end

twitPuzzle-server/app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

twitPuzzle-server/app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

twitPuzzle-server/app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
    <tr>
      <td><%= user.name %></td>
      <td><%= link_to 'Show', user %></td>
      <td><%= link_to 'Edit', edit_user_path(user) %></td>
      <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<br />

<%= link_to 'New User', new_user_path %>

twitPuzzle-server/app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

twitPuzzle-server/app/views/users/searchID.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
    </tr>
  </thead>

  <tbody>
    <tr>
      <td><%= user.name %></td>
    </tr>
    <% end %>
  </tbody>

</table>

<br />

<%= link_to 'New User', new_user_path %>

twitPuzzle-server/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %> |
<%= link_to 'Puzzels', user_puzzles_path(@user) %>