twitPuzzle-server/config/routes.rb
TwitPuzzle::Application.routes.draw do
  resources :rankings

  resources :users

  resources :users do
    resources :puzzles
  end
  resources :logins
  resources :friend do
    collection do
      get 'follow'
      get 'follower'
    end
  end

  resources :puzzles do
     member do
      get 'get_image'
     end
   end

resources :users do 
  resources :rankings
end

  resources :users do
    collection do
      get 'self_profile'
    end
  end

  TwitPuzzle::Application.routes.draw do
    get "rankings/eachRanking/:puzzle_id" => "rankings#eachRanking"
  end

  TwitPuzzle::Application.routes.draw do
    get "users/search/:name" => "users#searchID"
  end

  TwitPuzzle::Application.routes.draw do
    get "users/profile/self" => "users#self_profile"
  end

  TwitPuzzle::Application.routes.draw do
    get "puzzles/user/:user_id" => "puzzles#user_puzzle"
  end

  root to: 'logins#new'

end

twitPuzzle-server/app/models/puzzle.rb
class Puzzle < ActiveRecord::Base
	  belongs_to :user

	  def self.follow_timeline(user_id)
	  	puts "userID::",user_id
  		friends = Friend.where(user_id: user_id)
	  	num = friends.map{ |f|f.friend_id} 
	  	num.append(user_id)
	  	t = Puzzle.where("user_id in (?) ", num )
	    return t.sort{|a,b| b.created_at <=> a.created_at }
	  end

end

twitPuzzle-server/app/controllers/puzzles_controller.rb
class PuzzlesController < ApplicationController
  before_action :check_login
  before_action :set_puzzle, only: [:show, :edit, :update, :destroy]
  skip_before_action :verify_authenticity_token, lambda{|c| c.xml_http_request?}

  # GET /puzzles
  # GET /puzzles.json
  def index
    @puzzles = Puzzle.follow_timeline(session[:login])
    @puzzle_results = []
    for puzzle in @puzzles
      @puzzle_results.push(:id=>puzzle.id, :tweet=>puzzle.tweet, :image=>puzzle.image, :correct_order=>puzzle.correct_order, :name=>puzzle.user.name)
    end
  end

  def user_puzzle
      @puzzles = Puzzle.where("user_id=#{params[:user_id]}").order("created_at desc")
      @puzzle_results = []
      for puzzle in @puzzles
        @puzzle_results.push(:id=>puzzle.id, :tweet=>puzzle.tweet, :correct_order=>puzzle.correct_order, :name=>puzzle.user.name)
        puts "correct::", puzzle.correct_order
      end
  end

  # GET /puzzles/1
  # GET /puzzles/1.json
  def show
 
  end

  def get_image
   @puzzle = Puzzle.find(params[:id])
   send_data(@puzzle.image, :disposition => "inline", :type => "image/jpeg")
  end

  # GET /puzzles/new
  def new
    @puzzle = Puzzle.new
  end

  # GET /puzzles/1/edit
  def edit
  end

  # POST /puzzles
  # POST /puzzles.json
  def create
    @puzzle = Puzzle.new()
    puts "param:",params
    @puzzle.tweet = params[:puzzle][:tweet]
    @puzzle.correct_order = params[:puzzle][:correct_order]
    @puzzle.user_id = session[:login]

    if image = params[:puzzle][:image]
      @puzzle.image = image.read
    end

    respond_to do |format|
      if @puzzle.save
        format.html { redirect_to @puzzle, notice: 'Puzzle was successfully created.' }
        format.json { render action: 'show', status: :created, location: @puzzle }
      else
        format.html { render action: 'new' }
        format.json { render json: @puzzle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /puzzles/1
  # PATCH/PUT /puzzles/1.json
  def update
    respond_to do |format|
        image = nil
        if image = params[:puzzle][:image]
          image = image.read
        end

        if @puzzle.update(:tweet => params[:puzzle][:tweet], :image =>image)
        format.html { redirect_to @puzzle, notice: 'Puzzle was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @puzzle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /puzzles/1
  # DELETE /puzzles/1.json
  def destroy
    @puzzle.destroy
    respond_to do |format|
      format.html { redirect_to puzzles_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_puzzle
      @puzzle = Puzzle.find(params[:id])
    end
    

    def require_login
      if session[:login]
      else
        redirect_to new_login_path
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def puzzle_params
      params.require(:puzzle).permit(:tweet,:image)
    end

    def check_login

      puts session[:login]
      if session[:login]
        puts "aaaaaaaaaaaaaaaa"
        puts session[:login]
      else
        puts "session2:",session[:login]
        respond_to do |format|
            format.html { redirect_to new_login_path }
            format.json { head :no_content }
        end

      end

    end

end

twitPuzzle-server/app/helpers/puzzles_helper.rb
module PuzzlesHelper
end

twitPuzzle-server/app/views/puzzles/_form.html.erb
<%= form_for(@puzzle) do |f| %>
  <% if @puzzle.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@puzzle.errors.count, "error") %> prohibited this puzzle from being saved:</h2>

      <ul>
      <% @puzzle.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :tweet %><br />
    <%= f.text_field :tweet %>
  </div>

  <div class="field">
    <%= f.label :puzzle %><br />
    <%= f.file_field :image %>
  </div>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

twitPuzzle-server/app/views/puzzles/edit.html.erb
<h1>Editing puzzle</h1>

<%= render 'form' %>

<%= link_to 'Show', @puzzle %> |
<%= link_to 'Back', puzzles_path %>

twitPuzzle-server/app/views/puzzles/index.html.erb
<h1>Listing puzzles</h1>

<table>
  <thead>
    <tr>
      <th>Tweet</th>
      <th>Date</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @puzzles.each do |puzzle| %>
    <tr>
      <td><%= puzzle.user.name %></td>
      <td><%= puzzle.tweet %></td>
      <td><%= puzzle.created_at %></td>
      <td><%= image_tag(url_for(:action => 'get_image', :id => puzzle.id), :size => '100x100')%></td>
      <td><%= link_to 'Show', puzzle %></td>
      <td><%= link_to 'Edit', edit_puzzle_path(puzzle) %></td>
      <td><%= link_to 'Destroy', puzzle, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<br />

<%= link_to 'New Puzzle', new_puzzle_path %>
<%= link_to 'Logout', login_path(0), method: :delete %>

twitPuzzle-server/app/views/puzzles/new.html.erb
<h1>New puzzle</h1>

<%= render 'form' %>

<%= link_to 'Back', puzzles_path %>

twitPuzzle-server/app/views/puzzles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tweet:</strong>
  <%= @puzzle.tweet %> <br>
	<%= image_tag(url_for(:action => 'get_image', :id => @puzzle.id)) %>
</p>


<%= link_to 'Edit', edit_puzzle_path(@puzzle) %> |
<%= link_to 'Back', puzzles_path %>