twitPuzzle-server/config/routes.rb
TwitPuzzle::Application.routes.draw do
  resources :rankings

  resources :users

  resources :users do
    resources :puzzles
  end
  resources :logins
  resources :friend do
    collection do
      get 'follow'
      get 'follower'
    end
  end

  resources :puzzles do
     member do
      get 'get_image'
     end
   end

resources :users do 
  resources :rankings
end

  resources :users do
    collection do
      get 'self_profile'
    end
  end

  TwitPuzzle::Application.routes.draw do
    get "rankings/eachRanking/:puzzle_id" => "rankings#eachRanking"
  end

  TwitPuzzle::Application.routes.draw do
    get "users/search/:name" => "users#searchID"
  end

  TwitPuzzle::Application.routes.draw do
    get "users/profile/self" => "users#self_profile"
  end

  TwitPuzzle::Application.routes.draw do
    get "puzzles/user/:user_id" => "puzzles#user_puzzle"
  end

  root to: 'logins#new'

end

twitPuzzle-server/app/models/ranking.rb
class Ranking < ActiveRecord::Base
	  belongs_to :user
end

twitPuzzle-server/app/controllers/rankings_controller.rb
class RankingsController < ApplicationController
  before_action :set_ranking, only: [:show, :edit, :update, :destroy]

  # GET /rankings
  # GET /rankings.json
  def index
    @rankings = Ranking.all
  end

  # GET /rankings/1
  # GET /rankings/1.json
  def show
  end

  # GET /rankings/new
  def new
    @ranking = Ranking.new
  end

  # GET /rankings/1/edit
  def edit
  end

  def eachRanking
    results = Ranking.where("puzzle_id = '#{params[:puzzle_id]}'").order('complete_time asc')
     @rankings = []

    for result in results
      @user = User.find(result.user_id)
      @rankings.push(:puzzle_id=>result.puzzle_id, :user_id=> result.user_id, :complete_time=>result.complete_time, :user_name=>@user.name)
    end

#    @rankings = Ranking.where("puzzle_id = '#{params[:puzzle_id]}'").order('complete_time asc')

  end

  # POST /rankings
  # POST /rankings.json
  def create
    puts "create---------------------------------------------------"
    puts "nil?-",params[:ranking][:puzzle_id]
    puts "nil?-",params[:ranking][:complete_time]


    @ranking = Ranking.new(ranking_params)
    @ranking.puzzle_id = params[:ranking][:puzzle_id]
    @ranking.complete_time = params[:ranking][:complete_time]
    @ranking.user_id = session[:login]

    respond_to do |format|
      if @ranking.save
        format.html { redirect_to @ranking, notice: 'Ranking was successfully created.' }
        format.json { render action: 'show', status: :created, location: @ranking }
      else
        format.html { render action: 'new' }
        format.json { render json: @ranking.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rankings/1
  # PATCH/PUT /rankings/1.json
  def update
    respond_to do |format|
      if @ranking.update(ranking_params)
        format.html { redirect_to @ranking, notice: 'Ranking was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @ranking.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rankings/1
  # DELETE /rankings/1.json
  def destroy
    @ranking.destroy
    respond_to do |format|
      format.html { redirect_to rankings_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ranking
      @ranking = Ranking.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ranking_params
      params.require(:ranking).permit(:puzzle_id, :complete_time)
    end
end

twitPuzzle-server/app/helpers/rankings_helper.rb
module RankingsHelper
end

twitPuzzle-server/app/views/rankings/_form.html.erb
<%= form_for(@ranking) do |f| %>
  <% if @ranking.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ranking.errors.count, "error") %> prohibited this ranking from being saved:</h2>

      <ul>
      <% @ranking.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :complete_time %><br />
    <%= f.time_select :complete_time %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

twitPuzzle-server/app/views/rankings/eachRanking.html.erb
<h1>Listing rankings</h1>

<table>
  <thead>
    <tr>
      <th>パズルID</th>
      <th>タイム</th>
      <th>名前</th>
    </tr>
  </thead>
  <tbody>
    <% @rankings.each do |ranking| %>
    <tr>
    	<td><%= ranking[:puzzle_id] %></td>
      <td><%= ranking[:complete_time]%></td>
      <td><%= ranking[:user_name] %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<br />

<%= link_to 'New Ranking', new_ranking_path %>

twitPuzzle-server/app/views/rankings/edit.html.erb
<h1>Editing ranking</h1>

<%= render 'form' %>

<%= link_to 'Show', @ranking %> |
<%= link_to 'Back', rankings_path %>

twitPuzzle-server/app/views/rankings/index.html.erb
<h1>Listing rankings</h1>

<table>
  <thead>
    <tr>
      <th>Complete time</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @rankings.each do |ranking| %>
    <tr>
      <td><%= ranking.complete_time %></td>
      <td><%= link_to 'Show', ranking %></td>
      <td><%= link_to 'Edit', edit_ranking_path(ranking) %></td>
      <td><%= link_to 'Destroy', ranking, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<br />

<%= link_to 'New Ranking', new_ranking_path %>

twitPuzzle-server/app/views/rankings/new.html.erb
<h1>New ranking</h1>

<%= render 'form' %>

<%= link_to 'Back', rankings_path %>

twitPuzzle-server/app/views/rankings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Complete time:</strong>
  <%= @ranking.complete_time %>
</p>


<%= link_to 'Edit', edit_ranking_path(@ranking) %> |
<%= link_to 'Back', rankings_path %>